spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev	#开发环境
  application:
    name: spring-cloud2020-config-mqf-dev
---

spring:
  profiles: test	#测试环境
  application:
    name: spring-cloud2020-config-mqf-test
# 请保存UTF-8格式